logisticregression:
  filepath: 'db/eth_alabel_1h.csv'
  n_features: 60
  sentiment_add: [] # ['count', 'normalized']
  feature_columns: ['close', 'volume']
  model_filename: "models/model_logisticregression.joblib"
  start_date: '2019-09-17'
  end_date: '2024-11-25'

randomforest:
  filepath: 'db/eth_alabel_1h.csv'
  n_features: 60
  sentiment_add: [] # ['count', 'normalized']
  feature_columns: ['close', 'volume']
  model_filename: "models/model_randomforest.joblib"
  start_date: '2019-09-17'
  end_date: '2024-11-25'

xgboost:
  filepath: 'db/eth_alabel_1h.csv'
  n_features: 60
  sentiment_add: [] # ['count', 'normalized']
  feature_columns: ['close', 'volume']
  model_filename: "models/model_xgboost.joblib"
  start_date: '2019-09-17'
  end_date: '2024-11-25'

lstm:
  filepath: 'db/eth_alabel_1h.csv'
  n_features: 60
  feature_columns: ['close', 'volume'] # ['close', 'volume', 'count', 'normalized']
  best_model_path: 'models/model_lstm_senti.pth'
  start_date: '2019-09-17'
  end_date: '2024-11-25'
  epochs: 10
  batch_size: 8192
  hidden_dim: 64